AllCops:
  TargetRubyVersion: 2.6.5
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'notes/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Naming/MethodName:
  Exclude:
    - 'spec/**/*'
GlobalVars:
  AllowedVariables:
    - $PROGRAM_NAME
  
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
